-- =============================================================================
-- French Tech Next 40/120 — 2020 Cohort Import
-- =============================================================================
-- This migration:
--   1. Creates organizations that don't already exist (matched by slug)
--   2. Creates legal_entities where SIREN/SIRET data is available
--   3. Creates organization_programs entries for the 2020 cohort
-- =============================================================================

-- Ensure unaccent extension is available (already created in schema but safe to repeat)
CREATE EXTENSION IF NOT EXISTS "unaccent";

-- Step 1: Insert organizations (skip if slug already exists)
WITH ft2020 AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"Alan","website":null,"siren":"401386297","siret":"40138629700030","tier":"next40"},
      {"name":"Back Market","website":null,"siren":"834103111","siret":"83410311100029","tier":"next40"},
      {"name":"Believe","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"BioSerenity","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"BlaBlaCar","website":null,"siren":"491904546","siret":"49190454600034","tier":"next40"},
      {"name":"Cityscoot","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Contentsquare","website":null,"siren":"833654320","siret":"83365432000021","tier":"next40"},
      {"name":"Deezer","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Devialet","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Doctolib","website":null,"siren":"794598813","siret":"79459881300077","tier":"next40"},
      {"name":"Evaneos","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Finalcad","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Frichti","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"HomeExchange","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"HR Path","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"iAdvize","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Ivalua","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"JobTeaser","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Klaxoon","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Ledger","website":null,"siren":"529991119","siret":"52999111900098","tier":"next40"},
      {"name":"ManoMano","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Meero","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Mirakl","website":null,"siren":"530897990","siret":"53089799000079","tier":"next40"},
      {"name":"October","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"OpenClassrooms","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"OVH","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"PayFit","website":null,"siren":"813487899","siret":"81348789900060","tier":"next40"},
      {"name":"Recommerce","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Sendinblue","website":null,"siren":"821893286","siret":"82189328600061","tier":"next40"},
      {"name":"Shadow","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Shift Technology","website":null,"siren":"791862618","siret":"79186261800034","tier":"next40"},
      {"name":"Sigfox","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Talent.io","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Vade Secure","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Veepee","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Vestiaire Collective","website":null,"siren":"517465225","siret":"51746522500095","tier":"next40"},
      {"name":"Voodoo","website":null,"siren":"792483307","siret":"79248330700106","tier":"next40"},
      {"name":"Wynd","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Ynsect","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"Younited Credit","website":null,"siren":null,"siret":null,"tier":"next40"},
      {"name":"360Learning","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"AB Tasty","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Acticor Biotech","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Adyoulike","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Afyren","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Agriconomie","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Aircall","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Akeneo","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Aledia","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Alizé Pharma 3","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"All Mol Technology","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Amarisoft","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Anotherbrain","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Atempo Wooxo","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Biolog-id","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Botify","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Brut","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Certideal","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Comparateuragricole.com","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Cooptalis","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Crosscall","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Cubyn","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"CybelAngel","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Diabeloop","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Digital Insure","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"DNA Script","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Dreem","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Dynacure","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"EasyMile","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"EcoVadis","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"ekWateur","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"ENYO Pharma","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"ePack Hygiene","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Exotec Solutions","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Feed","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Flex Fuel Energy Development","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Fortia Financial Solutions","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Fretlink","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Happytal","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Heetch","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"HighLife","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Igyxos","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Ilek","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"ImCheck Therapeutics","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Inotrem","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"IPM France","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Kayrros","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Keranova","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Le Slip Français","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Lemon Way","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"LGO","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Lifen","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"LimFlow","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Loisirs Enchères","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Lumapps","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Lunchr","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Lydia","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Microphyt","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"MisterFly","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Mistertemp'","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Molotov","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Ornikar","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Papernest","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Perfectstay","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"PHENIX","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Platform.sh","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"QAPA","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Qare","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Qonto","website":null,"siren":"880118765","siret":"88011876500028","tier":"120"},
      {"name":"Reuniwatt","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"S4M","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Scality","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Saagie","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Spendesk","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Tabmo","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Talent.io","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Tissium","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Tree Frog Therapeutics","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Trusk","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Ubitransport","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Visiperf","website":null,"siren":null,"siret":null,"tier":"120"},
      {"name":"Yespark","website":null,"siren":null,"siret":null,"tier":"120"}
    ]$$
  ) AS (name TEXT, website TEXT, siren TEXT, siret TEXT, tier TEXT)
)
-- Step 1a: Create organizations that don't exist yet
INSERT INTO organizations (
  id, name, slug, organization_type, status, country,
  legacy_source, legacy_id, created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  s.name,
  lower(regexp_replace(
    regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
    '\s+', '-', 'g'
  )),
  'startup'::organization_type,
  'active'::organization_status,
  'France',
  'french_tech_next',
  s.siren,
  NOW(),
  NOW()
FROM ft2020 s
ON CONFLICT (slug) DO NOTHING;

-- Step 2: Create legal_entities for companies with SIREN data
WITH ft2020_siren AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"Alan","siren":"401386297","siret":"40138629700030"},
      {"name":"Back Market","siren":"834103111","siret":"83410311100029"},
      {"name":"BlaBlaCar","siren":"491904546","siret":"49190454600034"},
      {"name":"Contentsquare","siren":"833654320","siret":"83365432000021"},
      {"name":"Doctolib","siren":"794598813","siret":"79459881300077"},
      {"name":"Ledger","siren":"529991119","siret":"52999111900098"},
      {"name":"Mirakl","siren":"530897990","siret":"53089799000079"},
      {"name":"PayFit","siren":"813487899","siret":"81348789900060"},
      {"name":"Sendinblue","siren":"821893286","siret":"82189328600061"},
      {"name":"Shift Technology","siren":"791862618","siret":"79186261800034"},
      {"name":"Vestiaire Collective","siren":"517465225","siret":"51746522500095"},
      {"name":"Voodoo","siren":"792483307","siret":"79248330700106"},
      {"name":"Qonto","siren":"880118765","siret":"88011876500028"}
    ]$$
  ) AS (name TEXT, siren TEXT, siret TEXT)
)
INSERT INTO legal_entities (
  id, organization_id, legal_name, siren, siret, country, is_primary,
  created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  o.id,
  s.name,
  s.siren,
  s.siret,
  'France',
  TRUE,
  NOW(),
  NOW()
FROM ft2020_siren s
JOIN organizations o ON o.slug = lower(regexp_replace(
  regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
  '\s+', '-', 'g'
))
ON CONFLICT DO NOTHING;

-- Step 3: Create program entries for 2020 cohort
WITH ft2020_programs AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"Alan","tier":"next40"},
      {"name":"Back Market","tier":"next40"},
      {"name":"Believe","tier":"next40"},
      {"name":"BioSerenity","tier":"next40"},
      {"name":"BlaBlaCar","tier":"next40"},
      {"name":"Cityscoot","tier":"next40"},
      {"name":"Contentsquare","tier":"next40"},
      {"name":"Deezer","tier":"next40"},
      {"name":"Devialet","tier":"next40"},
      {"name":"Doctolib","tier":"next40"},
      {"name":"Evaneos","tier":"next40"},
      {"name":"Finalcad","tier":"next40"},
      {"name":"Frichti","tier":"next40"},
      {"name":"HomeExchange","tier":"next40"},
      {"name":"HR Path","tier":"next40"},
      {"name":"iAdvize","tier":"next40"},
      {"name":"Ivalua","tier":"next40"},
      {"name":"JobTeaser","tier":"next40"},
      {"name":"Klaxoon","tier":"next40"},
      {"name":"Ledger","tier":"next40"},
      {"name":"ManoMano","tier":"next40"},
      {"name":"Meero","tier":"next40"},
      {"name":"Mirakl","tier":"next40"},
      {"name":"October","tier":"next40"},
      {"name":"OpenClassrooms","tier":"next40"},
      {"name":"OVH","tier":"next40"},
      {"name":"PayFit","tier":"next40"},
      {"name":"Recommerce","tier":"next40"},
      {"name":"Sendinblue","tier":"next40"},
      {"name":"Shadow","tier":"next40"},
      {"name":"Shift Technology","tier":"next40"},
      {"name":"Sigfox","tier":"next40"},
      {"name":"Talent.io","tier":"next40"},
      {"name":"Vade Secure","tier":"next40"},
      {"name":"Veepee","tier":"next40"},
      {"name":"Vestiaire Collective","tier":"next40"},
      {"name":"Voodoo","tier":"next40"},
      {"name":"Wynd","tier":"next40"},
      {"name":"Ynsect","tier":"next40"},
      {"name":"Younited Credit","tier":"next40"},
      {"name":"360Learning","tier":"120"},
      {"name":"AB Tasty","tier":"120"},
      {"name":"Acticor Biotech","tier":"120"},
      {"name":"Adyoulike","tier":"120"},
      {"name":"Afyren","tier":"120"},
      {"name":"Agriconomie","tier":"120"},
      {"name":"Aircall","tier":"120"},
      {"name":"Akeneo","tier":"120"},
      {"name":"Aledia","tier":"120"},
      {"name":"Alizé Pharma 3","tier":"120"},
      {"name":"All Mol Technology","tier":"120"},
      {"name":"Amarisoft","tier":"120"},
      {"name":"Anotherbrain","tier":"120"},
      {"name":"Atempo Wooxo","tier":"120"},
      {"name":"Biolog-id","tier":"120"},
      {"name":"Botify","tier":"120"},
      {"name":"Brut","tier":"120"},
      {"name":"Certideal","tier":"120"},
      {"name":"Comparateuragricole.com","tier":"120"},
      {"name":"Cooptalis","tier":"120"},
      {"name":"Crosscall","tier":"120"},
      {"name":"Cubyn","tier":"120"},
      {"name":"CybelAngel","tier":"120"},
      {"name":"Diabeloop","tier":"120"},
      {"name":"Digital Insure","tier":"120"},
      {"name":"DNA Script","tier":"120"},
      {"name":"Dreem","tier":"120"},
      {"name":"Dynacure","tier":"120"},
      {"name":"EasyMile","tier":"120"},
      {"name":"EcoVadis","tier":"120"},
      {"name":"ekWateur","tier":"120"},
      {"name":"ENYO Pharma","tier":"120"},
      {"name":"ePack Hygiene","tier":"120"},
      {"name":"Exotec Solutions","tier":"120"},
      {"name":"Feed","tier":"120"},
      {"name":"Flex Fuel Energy Development","tier":"120"},
      {"name":"Fortia Financial Solutions","tier":"120"},
      {"name":"Fretlink","tier":"120"},
      {"name":"Happytal","tier":"120"},
      {"name":"Heetch","tier":"120"},
      {"name":"HighLife","tier":"120"},
      {"name":"Igyxos","tier":"120"},
      {"name":"Ilek","tier":"120"},
      {"name":"ImCheck Therapeutics","tier":"120"},
      {"name":"Inotrem","tier":"120"},
      {"name":"IPM France","tier":"120"},
      {"name":"Kayrros","tier":"120"},
      {"name":"Keranova","tier":"120"},
      {"name":"Le Slip Français","tier":"120"},
      {"name":"Lemon Way","tier":"120"},
      {"name":"LGO","tier":"120"},
      {"name":"Lifen","tier":"120"},
      {"name":"LimFlow","tier":"120"},
      {"name":"Loisirs Enchères","tier":"120"},
      {"name":"Lumapps","tier":"120"},
      {"name":"Lunchr","tier":"120"},
      {"name":"Lydia","tier":"120"},
      {"name":"Microphyt","tier":"120"},
      {"name":"MisterFly","tier":"120"},
      {"name":"Mistertemp'","tier":"120"},
      {"name":"Molotov","tier":"120"},
      {"name":"Ornikar","tier":"120"},
      {"name":"Papernest","tier":"120"},
      {"name":"Perfectstay","tier":"120"},
      {"name":"PHENIX","tier":"120"},
      {"name":"Platform.sh","tier":"120"},
      {"name":"QAPA","tier":"120"},
      {"name":"Qare","tier":"120"},
      {"name":"Qonto","tier":"120"},
      {"name":"Reuniwatt","tier":"120"},
      {"name":"S4M","tier":"120"},
      {"name":"Scality","tier":"120"},
      {"name":"Saagie","tier":"120"},
      {"name":"Spendesk","tier":"120"},
      {"name":"Tabmo","tier":"120"},
      {"name":"Talent.io","tier":"120"},
      {"name":"Tissium","tier":"120"},
      {"name":"Tree Frog Therapeutics","tier":"120"},
      {"name":"Trusk","tier":"120"},
      {"name":"Ubitransport","tier":"120"},
      {"name":"Visiperf","tier":"120"},
      {"name":"Yespark","tier":"120"}
    ]$$
  ) AS (name TEXT, tier TEXT)
)
INSERT INTO organization_programs (
  id, organization_id, program_name, tier, year, created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  o.id,
  'french_tech_next',
  s.tier,
  2020,
  NOW(),
  NOW()
FROM ft2020_programs s
JOIN organizations o ON o.slug = lower(regexp_replace(
  regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
  '\s+', '-', 'g'
))
ON CONFLICT (organization_id, program_name, year) DO NOTHING;
