-- =============================================================================
-- French Tech Next 40/120 — 2020 Cohort Import
-- =============================================================================
-- Imports companies for the 2020 cohort into:
--   1. organizations (creates if not existing, matched by slug)
--   2. legal_entities (where SIREN/SIRET available)
--   3. program_organizations (links to the 2020 program_edition)
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "unaccent";

-- Step 1: Insert organizations that don't exist yet
WITH ft2020 AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"Alan","website":null,"siren":"401386297","siret":"40138629700030","group_label":"Next 40"},
      {"name":"Back Market","website":null,"siren":"834103111","siret":"83410311100029","group_label":"Next 40"},
      {"name":"Believe","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"BioSerenity","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"BlaBlaCar","website":null,"siren":"491904546","siret":"49190454600034","group_label":"Next 40"},
      {"name":"Cityscoot","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Contentsquare","website":null,"siren":"833654320","siret":"83365432000021","group_label":"Next 40"},
      {"name":"Deezer","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Devialet","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Doctolib","website":null,"siren":"794598813","siret":"79459881300077","group_label":"Next 40"},
      {"name":"Evaneos","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Finalcad","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Frichti","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"HomeExchange","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"HR Path","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"iAdvize","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Ivalua","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"JobTeaser","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Klaxoon","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Ledger","website":null,"siren":"529991119","siret":"52999111900098","group_label":"Next 40"},
      {"name":"ManoMano","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Meero","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Mirakl","website":null,"siren":"530897990","siret":"53089799000079","group_label":"Next 40"},
      {"name":"October","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"OpenClassrooms","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"OVH","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"PayFit","website":null,"siren":"813487899","siret":"81348789900060","group_label":"Next 40"},
      {"name":"Recommerce","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Sendinblue","website":null,"siren":"821893286","siret":"82189328600061","group_label":"Next 40"},
      {"name":"Shadow","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Shift Technology","website":null,"siren":"791862618","siret":"79186261800034","group_label":"Next 40"},
      {"name":"Sigfox","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Talent.io","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Vade Secure","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Veepee","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Vestiaire Collective","website":null,"siren":"517465225","siret":"51746522500095","group_label":"Next 40"},
      {"name":"Voodoo","website":null,"siren":"792483307","siret":"79248330700106","group_label":"Next 40"},
      {"name":"Wynd","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Ynsect","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Younited Credit","website":null,"siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"360Learning","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"AB Tasty","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Acticor Biotech","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Adyoulike","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Afyren","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Agriconomie","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Aircall","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Akeneo","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Aledia","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Alizé Pharma 3","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"All Mol Technology","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Amarisoft","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Anotherbrain","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Atempo Wooxo","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Biolog-id","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Botify","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Brut","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Certideal","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Comparateuragricole.com","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Cooptalis","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Crosscall","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Cubyn","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"CybelAngel","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Diabeloop","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Digital Insure","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"DNA Script","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Dreem","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Dynacure","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"EasyMile","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"EcoVadis","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ekWateur","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ENYO Pharma","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ePack Hygiene","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Exotec Solutions","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Feed","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Flex Fuel Energy Development","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Fortia Financial Solutions","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Fretlink","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Happytal","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Heetch","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"HighLife","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Igyxos","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ilek","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ImCheck Therapeutics","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Inotrem","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"IPM France","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Kayrros","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Keranova","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Le Slip Français","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Lemon Way","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"LGO","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Lifen","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"LimFlow","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Loisirs Enchères","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Lumapps","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Lunchr","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Lydia","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Microphyt","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"MisterFly","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Mistertemp'","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Molotov","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ornikar","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Papernest","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Perfectstay","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"PHENIX","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Platform.sh","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"QAPA","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Qare","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Qonto","website":null,"siren":"880118765","siret":"88011876500028","group_label":"FT 120"},
      {"name":"Reuniwatt","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"S4M","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Scality","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Saagie","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Spendesk","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Tabmo","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Talent.io","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Tissium","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Tree Frog Therapeutics","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Trusk","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ubitransport","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Visiperf","website":null,"siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Yespark","website":null,"siren":null,"siret":null,"group_label":"FT 120"}
    ]$$
  ) AS (name TEXT, website TEXT, siren TEXT, siret TEXT, group_label TEXT)
)
INSERT INTO organizations (
  id, name, slug, organization_type, status, country,
  legacy_source, legacy_id, created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  s.name,
  lower(regexp_replace(
    regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
    '\s+', '-', 'g'
  )),
  'startup'::organization_type,
  'active'::organization_status,
  'France',
  'french_tech_next',
  s.siren,
  NOW(),
  NOW()
FROM ft2020 s
ON CONFLICT (slug) DO NOTHING;

-- Step 2: Create legal_entities for companies with SIREN data
WITH ft2020_siren AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"Alan","siren":"401386297","siret":"40138629700030"},
      {"name":"Back Market","siren":"834103111","siret":"83410311100029"},
      {"name":"BlaBlaCar","siren":"491904546","siret":"49190454600034"},
      {"name":"Contentsquare","siren":"833654320","siret":"83365432000021"},
      {"name":"Doctolib","siren":"794598813","siret":"79459881300077"},
      {"name":"Ledger","siren":"529991119","siret":"52999111900098"},
      {"name":"Mirakl","siren":"530897990","siret":"53089799000079"},
      {"name":"PayFit","siren":"813487899","siret":"81348789900060"},
      {"name":"Sendinblue","siren":"821893286","siret":"82189328600061"},
      {"name":"Shift Technology","siren":"791862618","siret":"79186261800034"},
      {"name":"Vestiaire Collective","siren":"517465225","siret":"51746522500095"},
      {"name":"Voodoo","siren":"792483307","siret":"79248330700106"},
      {"name":"Qonto","siren":"880118765","siret":"88011876500028"}
    ]$$
  ) AS (name TEXT, siren TEXT, siret TEXT)
)
INSERT INTO legal_entities (
  id, organization_id, legal_name, siren, siret, country, is_primary,
  created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  o.id,
  s.name,
  s.siren,
  s.siret,
  'France',
  TRUE,
  NOW(),
  NOW()
FROM ft2020_siren s
JOIN organizations o ON o.slug = lower(regexp_replace(
  regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
  '\s+', '-', 'g'
))
WHERE NOT EXISTS (
  SELECT 1 FROM legal_entities le
  WHERE le.organization_id = o.id AND le.siren = s.siren
);

-- Step 3: Create program_organizations entries for 2020 cohort
WITH ft2020_programs AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"Alan","group_label":"Next 40"},
      {"name":"Back Market","group_label":"Next 40"},
      {"name":"Believe","group_label":"Next 40"},
      {"name":"BioSerenity","group_label":"Next 40"},
      {"name":"BlaBlaCar","group_label":"Next 40"},
      {"name":"Cityscoot","group_label":"Next 40"},
      {"name":"Contentsquare","group_label":"Next 40"},
      {"name":"Deezer","group_label":"Next 40"},
      {"name":"Devialet","group_label":"Next 40"},
      {"name":"Doctolib","group_label":"Next 40"},
      {"name":"Evaneos","group_label":"Next 40"},
      {"name":"Finalcad","group_label":"Next 40"},
      {"name":"Frichti","group_label":"Next 40"},
      {"name":"HomeExchange","group_label":"Next 40"},
      {"name":"HR Path","group_label":"Next 40"},
      {"name":"iAdvize","group_label":"Next 40"},
      {"name":"Ivalua","group_label":"Next 40"},
      {"name":"JobTeaser","group_label":"Next 40"},
      {"name":"Klaxoon","group_label":"Next 40"},
      {"name":"Ledger","group_label":"Next 40"},
      {"name":"ManoMano","group_label":"Next 40"},
      {"name":"Meero","group_label":"Next 40"},
      {"name":"Mirakl","group_label":"Next 40"},
      {"name":"October","group_label":"Next 40"},
      {"name":"OpenClassrooms","group_label":"Next 40"},
      {"name":"OVH","group_label":"Next 40"},
      {"name":"PayFit","group_label":"Next 40"},
      {"name":"Recommerce","group_label":"Next 40"},
      {"name":"Sendinblue","group_label":"Next 40"},
      {"name":"Shadow","group_label":"Next 40"},
      {"name":"Shift Technology","group_label":"Next 40"},
      {"name":"Sigfox","group_label":"Next 40"},
      {"name":"Talent.io","group_label":"Next 40"},
      {"name":"Vade Secure","group_label":"Next 40"},
      {"name":"Veepee","group_label":"Next 40"},
      {"name":"Vestiaire Collective","group_label":"Next 40"},
      {"name":"Voodoo","group_label":"Next 40"},
      {"name":"Wynd","group_label":"Next 40"},
      {"name":"Ynsect","group_label":"Next 40"},
      {"name":"Younited Credit","group_label":"Next 40"},
      {"name":"360Learning","group_label":"FT 120"},
      {"name":"AB Tasty","group_label":"FT 120"},
      {"name":"Acticor Biotech","group_label":"FT 120"},
      {"name":"Adyoulike","group_label":"FT 120"},
      {"name":"Afyren","group_label":"FT 120"},
      {"name":"Agriconomie","group_label":"FT 120"},
      {"name":"Aircall","group_label":"FT 120"},
      {"name":"Akeneo","group_label":"FT 120"},
      {"name":"Aledia","group_label":"FT 120"},
      {"name":"Alizé Pharma 3","group_label":"FT 120"},
      {"name":"All Mol Technology","group_label":"FT 120"},
      {"name":"Amarisoft","group_label":"FT 120"},
      {"name":"Anotherbrain","group_label":"FT 120"},
      {"name":"Atempo Wooxo","group_label":"FT 120"},
      {"name":"Biolog-id","group_label":"FT 120"},
      {"name":"Botify","group_label":"FT 120"},
      {"name":"Brut","group_label":"FT 120"},
      {"name":"Certideal","group_label":"FT 120"},
      {"name":"Comparateuragricole.com","group_label":"FT 120"},
      {"name":"Cooptalis","group_label":"FT 120"},
      {"name":"Crosscall","group_label":"FT 120"},
      {"name":"Cubyn","group_label":"FT 120"},
      {"name":"CybelAngel","group_label":"FT 120"},
      {"name":"Diabeloop","group_label":"FT 120"},
      {"name":"Digital Insure","group_label":"FT 120"},
      {"name":"DNA Script","group_label":"FT 120"},
      {"name":"Dreem","group_label":"FT 120"},
      {"name":"Dynacure","group_label":"FT 120"},
      {"name":"EasyMile","group_label":"FT 120"},
      {"name":"EcoVadis","group_label":"FT 120"},
      {"name":"ekWateur","group_label":"FT 120"},
      {"name":"ENYO Pharma","group_label":"FT 120"},
      {"name":"ePack Hygiene","group_label":"FT 120"},
      {"name":"Exotec Solutions","group_label":"FT 120"},
      {"name":"Feed","group_label":"FT 120"},
      {"name":"Flex Fuel Energy Development","group_label":"FT 120"},
      {"name":"Fortia Financial Solutions","group_label":"FT 120"},
      {"name":"Fretlink","group_label":"FT 120"},
      {"name":"Happytal","group_label":"FT 120"},
      {"name":"Heetch","group_label":"FT 120"},
      {"name":"HighLife","group_label":"FT 120"},
      {"name":"Igyxos","group_label":"FT 120"},
      {"name":"Ilek","group_label":"FT 120"},
      {"name":"ImCheck Therapeutics","group_label":"FT 120"},
      {"name":"Inotrem","group_label":"FT 120"},
      {"name":"IPM France","group_label":"FT 120"},
      {"name":"Kayrros","group_label":"FT 120"},
      {"name":"Keranova","group_label":"FT 120"},
      {"name":"Le Slip Français","group_label":"FT 120"},
      {"name":"Lemon Way","group_label":"FT 120"},
      {"name":"LGO","group_label":"FT 120"},
      {"name":"Lifen","group_label":"FT 120"},
      {"name":"LimFlow","group_label":"FT 120"},
      {"name":"Loisirs Enchères","group_label":"FT 120"},
      {"name":"Lumapps","group_label":"FT 120"},
      {"name":"Lunchr","group_label":"FT 120"},
      {"name":"Lydia","group_label":"FT 120"},
      {"name":"Microphyt","group_label":"FT 120"},
      {"name":"MisterFly","group_label":"FT 120"},
      {"name":"Mistertemp'","group_label":"FT 120"},
      {"name":"Molotov","group_label":"FT 120"},
      {"name":"Ornikar","group_label":"FT 120"},
      {"name":"Papernest","group_label":"FT 120"},
      {"name":"Perfectstay","group_label":"FT 120"},
      {"name":"PHENIX","group_label":"FT 120"},
      {"name":"Platform.sh","group_label":"FT 120"},
      {"name":"QAPA","group_label":"FT 120"},
      {"name":"Qare","group_label":"FT 120"},
      {"name":"Qonto","group_label":"FT 120"},
      {"name":"Reuniwatt","group_label":"FT 120"},
      {"name":"S4M","group_label":"FT 120"},
      {"name":"Scality","group_label":"FT 120"},
      {"name":"Saagie","group_label":"FT 120"},
      {"name":"Spendesk","group_label":"FT 120"},
      {"name":"Tabmo","group_label":"FT 120"},
      {"name":"Talent.io","group_label":"FT 120"},
      {"name":"Tissium","group_label":"FT 120"},
      {"name":"Tree Frog Therapeutics","group_label":"FT 120"},
      {"name":"Trusk","group_label":"FT 120"},
      {"name":"Ubitransport","group_label":"FT 120"},
      {"name":"Visiperf","group_label":"FT 120"},
      {"name":"Yespark","group_label":"FT 120"}
    ]$$
  ) AS (name TEXT, group_label TEXT)
)
INSERT INTO program_organizations (
  id, program_edition_id, organization_id, group_label, legacy_source,
  created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  pe.id,
  o.id,
  s.group_label,
  'french_tech_next',
  NOW(),
  NOW()
FROM ft2020_programs s
JOIN organizations o ON o.slug = lower(regexp_replace(
  regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
  '\s+', '-', 'g'
))
JOIN program_editions pe ON pe.slug = 'french-tech-next40-120-2020'
ON CONFLICT (program_edition_id, organization_id) DO NOTHING;
