-- =============================================================================
-- French Tech Next 40/120 — 2021 Cohort Import
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "unaccent";

-- Step 1: Insert organizations that don't exist yet
WITH ft2021 AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"AB Tasty","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Akeneo","siren":"790672588","siret":"79067258800031","group_label":"Next 40"},
      {"name":"Alan","siren":"401386297","siret":"40138629700030","group_label":"Next 40"},
      {"name":"Aledia","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Back Market","siren":"834103111","siret":"83410311100029","group_label":"Next 40"},
      {"name":"Believe","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"BioSerenity","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"BlaBlaCar","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Brut","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Cityscoot","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Contentsquare","siren":"833654320","siret":"83365432000021","group_label":"Next 40"},
      {"name":"CybelAngel","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Deezer","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Doctolib","siren":"794598813","siret":"79459881300077","group_label":"Next 40"},
      {"name":"Evaneos","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Exotec Solutions","siren":"812878742","siret":"81287874200053","group_label":"Next 40"},
      {"name":"Heetch","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Ivalua","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"JobTeaser","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Kineis","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Klaxoon","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Lumapps","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Lydia","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"ManoMano","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Meero","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Mirakl","siren":"530897990","siret":"53089799000079","group_label":"Next 40"},
      {"name":"October","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"OpenClassrooms","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"OVH","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"PayFit","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Qonto","siren":"880118765","siret":"88011876500028","group_label":"Next 40"},
      {"name":"Sendinblue","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Shift Technology","siren":"791862618","siret":"79186261800034","group_label":"Next 40"},
      {"name":"Skeepers","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Veepee","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Voodoo","siren":"792483307","siret":"79248330700106","group_label":"Next 40"},
      {"name":"Wynd","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Ynsect","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Younited Credit","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Yubo","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Afyren","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Agriconomie","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"All Mol Technology","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Alma","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Amarisoft","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ankorstore","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Biolog-id","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Blade","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Certideal","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Cooptalis","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"CorWave","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Devialet","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"DNA Script","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Dreem","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Dynacure","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"EcoVadis","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ekWateur","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Enterome","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ENYO Pharma","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Eyevensys","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Finalcad","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Flex Fuel Energy Development","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Flying Whales","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Frichti","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Geosat","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Gojob","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Happn","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Happytal","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Hoppen","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"HR Path","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"iAdvize","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Igyxos","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ilek","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ImCheck Therapeutics","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Innovafeed","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Inotrem","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Joone","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Keranova","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Kovers","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ledger","siren":"529991119","siret":"52999111900098","group_label":"FT 120"},
      {"name":"Lemon Way","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Luko","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Madbox","siren":"807743844","siret":"80774384400027","group_label":"FT 120"},
      {"name":"Medadom","siren":"981538275","siret":"98153827500018","group_label":"FT 120"},
      {"name":"Meero","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Meilleurtaux","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Microphyt","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"MisterFly","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Mistertemp' group","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Molotov","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"MWM","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Okwind","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ornikar","siren":"818583130","siret":"81858313000013","group_label":"FT 120"},
      {"name":"Papernest","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Perfectstay","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Pharmedistore","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Platform.sh","siren":"521496059","siret":"52149605900044","group_label":"FT 120"},
      {"name":"QAPA","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Qare","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Recommerce","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Reuniwatt","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Robocath","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"S4M","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Scality","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Selectra","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Sigfox","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"SparingVision","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Spendesk","siren":"821893286","siret":"82189328600061","group_label":"FT 120"},
      {"name":"Swile","siren":"824012173","siret":"82401217300046","group_label":"FT 120"},
      {"name":"TalentSoft","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Tissium","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Trusk","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ubitransport","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ultra Premium Direct","siren":"799071253","siret":"79907125300030","group_label":"FT 120"},
      {"name":"Vade Secure","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Vestiaire Collective","siren":"517465225","siret":"51746522500095","group_label":"FT 120"},
      {"name":"Virtuo","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Withings","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Worldia","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Younited Credit","siren":null,"siret":null,"group_label":"FT 120"}
    ]$$
  ) AS (name TEXT, siren TEXT, siret TEXT, group_label TEXT)
)
INSERT INTO organizations (
  id, name, slug, organization_type, status, country,
  legacy_source, legacy_id, created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  s.name,
  lower(regexp_replace(
    regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
    '\s+', '-', 'g'
  )),
  'startup'::organization_type,
  'active'::organization_status,
  'France',
  'french_tech_next',
  s.siren,
  NOW(),
  NOW()
FROM ft2021 s
ON CONFLICT (slug) DO NOTHING;

-- Step 2: Create legal_entities for companies with SIREN data
WITH ft2021_siren AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"Akeneo","siren":"790672588","siret":"79067258800031"},
      {"name":"Alan","siren":"401386297","siret":"40138629700030"},
      {"name":"Back Market","siren":"834103111","siret":"83410311100029"},
      {"name":"Contentsquare","siren":"833654320","siret":"83365432000021"},
      {"name":"Doctolib","siren":"794598813","siret":"79459881300077"},
      {"name":"Exotec Solutions","siren":"812878742","siret":"81287874200053"},
      {"name":"Mirakl","siren":"530897990","siret":"53089799000079"},
      {"name":"Qonto","siren":"880118765","siret":"88011876500028"},
      {"name":"Shift Technology","siren":"791862618","siret":"79186261800034"},
      {"name":"Voodoo","siren":"792483307","siret":"79248330700106"},
      {"name":"Ledger","siren":"529991119","siret":"52999111900098"},
      {"name":"Madbox","siren":"807743844","siret":"80774384400027"},
      {"name":"Medadom","siren":"981538275","siret":"98153827500018"},
      {"name":"Ornikar","siren":"818583130","siret":"81858313000013"},
      {"name":"Platform.sh","siren":"521496059","siret":"52149605900044"},
      {"name":"Spendesk","siren":"821893286","siret":"82189328600061"},
      {"name":"Swile","siren":"824012173","siret":"82401217300046"},
      {"name":"Ultra Premium Direct","siren":"799071253","siret":"79907125300030"},
      {"name":"Vestiaire Collective","siren":"517465225","siret":"51746522500095"}
    ]$$
  ) AS (name TEXT, siren TEXT, siret TEXT)
)
INSERT INTO legal_entities (
  id, organization_id, legal_name, siren, siret, country, is_primary,
  created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  o.id,
  s.name,
  s.siren,
  s.siret,
  'France',
  TRUE,
  NOW(),
  NOW()
FROM ft2021_siren s
JOIN organizations o ON o.slug = lower(regexp_replace(
  regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
  '\s+', '-', 'g'
))
WHERE NOT EXISTS (
  SELECT 1 FROM legal_entities le
  WHERE le.organization_id = o.id AND le.siren = s.siren
);

-- Step 3: Create program_organizations entries for 2021 cohort
WITH ft2021_programs AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"AB Tasty","group_label":"Next 40"},
      {"name":"Akeneo","group_label":"Next 40"},
      {"name":"Alan","group_label":"Next 40"},
      {"name":"Aledia","group_label":"Next 40"},
      {"name":"Back Market","group_label":"Next 40"},
      {"name":"Believe","group_label":"Next 40"},
      {"name":"BioSerenity","group_label":"Next 40"},
      {"name":"BlaBlaCar","group_label":"Next 40"},
      {"name":"Brut","group_label":"Next 40"},
      {"name":"Cityscoot","group_label":"Next 40"},
      {"name":"Contentsquare","group_label":"Next 40"},
      {"name":"CybelAngel","group_label":"Next 40"},
      {"name":"Deezer","group_label":"Next 40"},
      {"name":"Doctolib","group_label":"Next 40"},
      {"name":"Evaneos","group_label":"Next 40"},
      {"name":"Exotec Solutions","group_label":"Next 40"},
      {"name":"Heetch","group_label":"Next 40"},
      {"name":"Ivalua","group_label":"Next 40"},
      {"name":"JobTeaser","group_label":"Next 40"},
      {"name":"Kineis","group_label":"Next 40"},
      {"name":"Klaxoon","group_label":"Next 40"},
      {"name":"Lumapps","group_label":"Next 40"},
      {"name":"Lydia","group_label":"Next 40"},
      {"name":"ManoMano","group_label":"Next 40"},
      {"name":"Meero","group_label":"Next 40"},
      {"name":"Mirakl","group_label":"Next 40"},
      {"name":"October","group_label":"Next 40"},
      {"name":"OpenClassrooms","group_label":"Next 40"},
      {"name":"OVH","group_label":"Next 40"},
      {"name":"PayFit","group_label":"Next 40"},
      {"name":"Qonto","group_label":"Next 40"},
      {"name":"Sendinblue","group_label":"Next 40"},
      {"name":"Shift Technology","group_label":"Next 40"},
      {"name":"Skeepers","group_label":"Next 40"},
      {"name":"Veepee","group_label":"Next 40"},
      {"name":"Voodoo","group_label":"Next 40"},
      {"name":"Wynd","group_label":"Next 40"},
      {"name":"Ynsect","group_label":"Next 40"},
      {"name":"Younited Credit","group_label":"Next 40"},
      {"name":"Yubo","group_label":"Next 40"},
      {"name":"Afyren","group_label":"FT 120"},
      {"name":"Agriconomie","group_label":"FT 120"},
      {"name":"All Mol Technology","group_label":"FT 120"},
      {"name":"Alma","group_label":"FT 120"},
      {"name":"Amarisoft","group_label":"FT 120"},
      {"name":"Ankorstore","group_label":"FT 120"},
      {"name":"Biolog-id","group_label":"FT 120"},
      {"name":"Blade","group_label":"FT 120"},
      {"name":"Certideal","group_label":"FT 120"},
      {"name":"Cooptalis","group_label":"FT 120"},
      {"name":"CorWave","group_label":"FT 120"},
      {"name":"Devialet","group_label":"FT 120"},
      {"name":"DNA Script","group_label":"FT 120"},
      {"name":"Dreem","group_label":"FT 120"},
      {"name":"Dynacure","group_label":"FT 120"},
      {"name":"EcoVadis","group_label":"FT 120"},
      {"name":"ekWateur","group_label":"FT 120"},
      {"name":"Enterome","group_label":"FT 120"},
      {"name":"ENYO Pharma","group_label":"FT 120"},
      {"name":"Eyevensys","group_label":"FT 120"},
      {"name":"Finalcad","group_label":"FT 120"},
      {"name":"Flex Fuel Energy Development","group_label":"FT 120"},
      {"name":"Flying Whales","group_label":"FT 120"},
      {"name":"Frichti","group_label":"FT 120"},
      {"name":"Geosat","group_label":"FT 120"},
      {"name":"Gojob","group_label":"FT 120"},
      {"name":"Happn","group_label":"FT 120"},
      {"name":"Happytal","group_label":"FT 120"},
      {"name":"Hoppen","group_label":"FT 120"},
      {"name":"HR Path","group_label":"FT 120"},
      {"name":"iAdvize","group_label":"FT 120"},
      {"name":"Igyxos","group_label":"FT 120"},
      {"name":"Ilek","group_label":"FT 120"},
      {"name":"ImCheck Therapeutics","group_label":"FT 120"},
      {"name":"Innovafeed","group_label":"FT 120"},
      {"name":"Inotrem","group_label":"FT 120"},
      {"name":"Joone","group_label":"FT 120"},
      {"name":"Keranova","group_label":"FT 120"},
      {"name":"Kovers","group_label":"FT 120"},
      {"name":"Ledger","group_label":"FT 120"},
      {"name":"Lemon Way","group_label":"FT 120"},
      {"name":"Luko","group_label":"FT 120"},
      {"name":"Madbox","group_label":"FT 120"},
      {"name":"Medadom","group_label":"FT 120"},
      {"name":"Meero","group_label":"FT 120"},
      {"name":"Meilleurtaux","group_label":"FT 120"},
      {"name":"Microphyt","group_label":"FT 120"},
      {"name":"MisterFly","group_label":"FT 120"},
      {"name":"Mistertemp' group","group_label":"FT 120"},
      {"name":"Molotov","group_label":"FT 120"},
      {"name":"MWM","group_label":"FT 120"},
      {"name":"Okwind","group_label":"FT 120"},
      {"name":"Ornikar","group_label":"FT 120"},
      {"name":"Papernest","group_label":"FT 120"},
      {"name":"Perfectstay","group_label":"FT 120"},
      {"name":"Pharmedistore","group_label":"FT 120"},
      {"name":"Platform.sh","group_label":"FT 120"},
      {"name":"QAPA","group_label":"FT 120"},
      {"name":"Qare","group_label":"FT 120"},
      {"name":"Recommerce","group_label":"FT 120"},
      {"name":"Reuniwatt","group_label":"FT 120"},
      {"name":"Robocath","group_label":"FT 120"},
      {"name":"S4M","group_label":"FT 120"},
      {"name":"Scality","group_label":"FT 120"},
      {"name":"Selectra","group_label":"FT 120"},
      {"name":"Sigfox","group_label":"FT 120"},
      {"name":"SparingVision","group_label":"FT 120"},
      {"name":"Spendesk","group_label":"FT 120"},
      {"name":"Swile","group_label":"FT 120"},
      {"name":"TalentSoft","group_label":"FT 120"},
      {"name":"Tissium","group_label":"FT 120"},
      {"name":"Trusk","group_label":"FT 120"},
      {"name":"Ubitransport","group_label":"FT 120"},
      {"name":"Ultra Premium Direct","group_label":"FT 120"},
      {"name":"Vade Secure","group_label":"FT 120"},
      {"name":"Vestiaire Collective","group_label":"FT 120"},
      {"name":"Virtuo","group_label":"FT 120"},
      {"name":"Withings","group_label":"FT 120"},
      {"name":"Worldia","group_label":"FT 120"},
      {"name":"Younited Credit","group_label":"FT 120"}
    ]$$
  ) AS (name TEXT, group_label TEXT)
)
INSERT INTO program_organizations (
  id, program_edition_id, organization_id, group_label, legacy_source,
  created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  pe.id,
  o.id,
  s.group_label,
  'french_tech_next',
  NOW(),
  NOW()
FROM ft2021_programs s
JOIN organizations o ON o.slug = lower(regexp_replace(
  regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
  '\s+', '-', 'g'
))
JOIN program_editions pe ON pe.slug = 'french-tech-next40-120-2021'
ON CONFLICT (program_edition_id, organization_id) DO NOTHING;
