-- =============================================================================
-- French Tech Next 40/120 — 2022 Cohort Import
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "unaccent";

-- Step 1: Insert organizations that don't exist yet
WITH ft2022 AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"360Learning","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Alan","siren":"401386297","siret":"40138629700030","group_label":"Next 40"},
      {"name":"Aledia","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Alma","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Ankorstore","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"BioSerenity","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"BlaBlaCar","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Brut","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Contentsquare","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Deezer","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"DentalMonitoring","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Descartes Underwriting","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"DNA Script","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Doctolib","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Exotec","siren":"812878742","siret":"81287874200053","group_label":"Next 40"},
      {"name":"IAD France","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Ivalua","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Kineis","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Ledger","siren":"529991119","siret":"52999111900098","group_label":"Next 40"},
      {"name":"Lifen","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Loft Orbital Solutions","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Lumapps","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Lydia","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Malt","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"ManoMano","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Meero","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Mirakl","siren":"530897990","siret":"53089799000079","group_label":"Next 40"},
      {"name":"Ornikar","siren":"818583130","siret":"81858313000013","group_label":"Next 40"},
      {"name":"PayFit","siren":"813487899","siret":"81348789900060","group_label":"Next 40"},
      {"name":"Qonto","siren":"880118765","siret":"88011876500028","group_label":"Next 40"},
      {"name":"Shift Technology","siren":"791862618","siret":"79186261800034","group_label":"Next 40"},
      {"name":"Skeepers","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Sorare","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Spendesk","siren":"821893286","siret":"82189328600061","group_label":"Next 40"},
      {"name":"Swile","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Veepee","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Vestiaire Collective","siren":"517465225","siret":"51746522500095","group_label":"Next 40"},
      {"name":"Voodoo","siren":"792483307","siret":"79248330700106","group_label":"Next 40"},
      {"name":"Ynsect","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Younited Credit","siren":null,"siret":null,"group_label":"Next 40"},
      {"name":"Adikteev","siren":"789514619","siret":"78951461900061","group_label":"FT 120"},
      {"name":"Agicap","siren":"823248703","siret":"82324870300063","group_label":"FT 120"},
      {"name":"Agriconomie","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Akeneo","siren":"790672588","siret":"79067258800031","group_label":"FT 120"},
      {"name":"All Mol Technology","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Iziwork","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Amarisoft","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Amolyt Pharma","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Back Market","siren":"834103111","siret":"83410311100029","group_label":"FT 120"},
      {"name":"Botify","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Certideal","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Cooptalis","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"CorWave","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Crosscall","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Cubyn","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Devialet","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"E.Z Drive","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"EcoVadis","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ekWateur","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Geosat","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"GitGuardian","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Gojob","siren":"813454717","siret":"81345471700055","group_label":"FT 120"},
      {"name":"Happn","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Heetch","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"HOMA","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Hoppen","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"HR Path","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Hubside","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"iAdvize","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Igyxos","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ilek","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"ImCheck Therapeutics","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Innovafeed","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Inotrem","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"JobTeaser","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Joone","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Klaxoon","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"La Belle Vie","siren":"982293524","siret":"98229352400012","group_label":"FT 120"},
      {"name":"Leocare","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Libon","siren":"841292691","siret":"84129269100018","group_label":"FT 120"},
      {"name":"Luko","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Madbox","siren":"807743844","siret":"80774384400027","group_label":"FT 120"},
      {"name":"Medadom","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Meilleurtaux","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Mnemo Therapeutics","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"MWM","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"MYM","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"NW","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Okwind","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"OpenClassrooms","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Papernest","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Pennylane","siren":"503161580","siret":"50316158000066","group_label":"FT 120"},
      {"name":"Perfectstay","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Pharmedistore","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Pigment","siren":"941429565","siret":"94142956500026","group_label":"FT 120"},
      {"name":"Platform.sh","siren":"521496059","siret":"52149605900044","group_label":"FT 120"},
      {"name":"PlayPlay","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Recommerce","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Selectra","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Sendinblue","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Singulart","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Skello","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Smallable","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Equativ","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"SparingVision","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Tissium","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Tree Frog Therapeutics","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Trusk","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ubitransport","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Ultra Premium Direct","siren":"799071253","siret":"79907125300030","group_label":"FT 120"},
      {"name":"Vade Secure","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Verkor","siren":"888047792","siret":"88804779200039","group_label":"FT 120"},
      {"name":"Virtuo","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Visiperf","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Wandercraft","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Withings","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Woosmap","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Wynd","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Yousign","siren":null,"siret":null,"group_label":"FT 120"},
      {"name":"Yubo","siren":"810283507","siret":"81028350700038","group_label":"FT 120"}
    ]$$
  ) AS (name TEXT, siren TEXT, siret TEXT, group_label TEXT)
)
INSERT INTO organizations (
  id, name, slug, organization_type, status, country,
  legacy_source, legacy_id, created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  s.name,
  lower(regexp_replace(
    regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
    '\s+', '-', 'g'
  )),
  'startup'::organization_type,
  'active'::organization_status,
  'France',
  'french_tech_next',
  s.siren,
  NOW(),
  NOW()
FROM ft2022 s
ON CONFLICT (slug) DO NOTHING;

-- Step 2: Create legal_entities for companies with SIREN data
WITH ft2022_siren AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"Alan","siren":"401386297","siret":"40138629700030"},
      {"name":"Exotec","siren":"812878742","siret":"81287874200053"},
      {"name":"Ledger","siren":"529991119","siret":"52999111900098"},
      {"name":"Mirakl","siren":"530897990","siret":"53089799000079"},
      {"name":"Ornikar","siren":"818583130","siret":"81858313000013"},
      {"name":"PayFit","siren":"813487899","siret":"81348789900060"},
      {"name":"Qonto","siren":"880118765","siret":"88011876500028"},
      {"name":"Shift Technology","siren":"791862618","siret":"79186261800034"},
      {"name":"Spendesk","siren":"821893286","siret":"82189328600061"},
      {"name":"Vestiaire Collective","siren":"517465225","siret":"51746522500095"},
      {"name":"Voodoo","siren":"792483307","siret":"79248330700106"},
      {"name":"Adikteev","siren":"789514619","siret":"78951461900061"},
      {"name":"Agicap","siren":"823248703","siret":"82324870300063"},
      {"name":"Akeneo","siren":"790672588","siret":"79067258800031"},
      {"name":"Back Market","siren":"834103111","siret":"83410311100029"},
      {"name":"Gojob","siren":"813454717","siret":"81345471700055"},
      {"name":"La Belle Vie","siren":"982293524","siret":"98229352400012"},
      {"name":"Libon","siren":"841292691","siret":"84129269100018"},
      {"name":"Madbox","siren":"807743844","siret":"80774384400027"},
      {"name":"Pennylane","siren":"503161580","siret":"50316158000066"},
      {"name":"Pigment","siren":"941429565","siret":"94142956500026"},
      {"name":"Platform.sh","siren":"521496059","siret":"52149605900044"},
      {"name":"Ultra Premium Direct","siren":"799071253","siret":"79907125300030"},
      {"name":"Verkor","siren":"888047792","siret":"88804779200039"},
      {"name":"Yubo","siren":"810283507","siret":"81028350700038"}
    ]$$
  ) AS (name TEXT, siren TEXT, siret TEXT)
)
INSERT INTO legal_entities (
  id, organization_id, legal_name, siren, siret, country, is_primary,
  created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  o.id,
  s.name,
  s.siren,
  s.siret,
  'France',
  TRUE,
  NOW(),
  NOW()
FROM ft2022_siren s
JOIN organizations o ON o.slug = lower(regexp_replace(
  regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
  '\s+', '-', 'g'
))
WHERE NOT EXISTS (
  SELECT 1 FROM legal_entities le
  WHERE le.organization_id = o.id AND le.siren = s.siren
);

-- Step 3: Create program_organizations entries for 2022 cohort
WITH ft2022_programs AS (
  SELECT * FROM json_populate_recordset(
    NULL::record,
    $$[
      {"name":"360Learning","group_label":"Next 40"},
      {"name":"Alan","group_label":"Next 40"},
      {"name":"Aledia","group_label":"Next 40"},
      {"name":"Alma","group_label":"Next 40"},
      {"name":"Ankorstore","group_label":"Next 40"},
      {"name":"BioSerenity","group_label":"Next 40"},
      {"name":"BlaBlaCar","group_label":"Next 40"},
      {"name":"Brut","group_label":"Next 40"},
      {"name":"Contentsquare","group_label":"Next 40"},
      {"name":"Deezer","group_label":"Next 40"},
      {"name":"DentalMonitoring","group_label":"Next 40"},
      {"name":"Descartes Underwriting","group_label":"Next 40"},
      {"name":"DNA Script","group_label":"Next 40"},
      {"name":"Doctolib","group_label":"Next 40"},
      {"name":"Exotec","group_label":"Next 40"},
      {"name":"IAD France","group_label":"Next 40"},
      {"name":"Ivalua","group_label":"Next 40"},
      {"name":"Kineis","group_label":"Next 40"},
      {"name":"Ledger","group_label":"Next 40"},
      {"name":"Lifen","group_label":"Next 40"},
      {"name":"Loft Orbital Solutions","group_label":"Next 40"},
      {"name":"Lumapps","group_label":"Next 40"},
      {"name":"Lydia","group_label":"Next 40"},
      {"name":"Malt","group_label":"Next 40"},
      {"name":"ManoMano","group_label":"Next 40"},
      {"name":"Meero","group_label":"Next 40"},
      {"name":"Mirakl","group_label":"Next 40"},
      {"name":"Ornikar","group_label":"Next 40"},
      {"name":"PayFit","group_label":"Next 40"},
      {"name":"Qonto","group_label":"Next 40"},
      {"name":"Shift Technology","group_label":"Next 40"},
      {"name":"Skeepers","group_label":"Next 40"},
      {"name":"Sorare","group_label":"Next 40"},
      {"name":"Spendesk","group_label":"Next 40"},
      {"name":"Swile","group_label":"Next 40"},
      {"name":"Veepee","group_label":"Next 40"},
      {"name":"Vestiaire Collective","group_label":"Next 40"},
      {"name":"Voodoo","group_label":"Next 40"},
      {"name":"Ynsect","group_label":"Next 40"},
      {"name":"Younited Credit","group_label":"Next 40"},
      {"name":"Adikteev","group_label":"FT 120"},
      {"name":"Agicap","group_label":"FT 120"},
      {"name":"Agriconomie","group_label":"FT 120"},
      {"name":"Akeneo","group_label":"FT 120"},
      {"name":"All Mol Technology","group_label":"FT 120"},
      {"name":"Iziwork","group_label":"FT 120"},
      {"name":"Amarisoft","group_label":"FT 120"},
      {"name":"Amolyt Pharma","group_label":"FT 120"},
      {"name":"Back Market","group_label":"FT 120"},
      {"name":"Botify","group_label":"FT 120"},
      {"name":"Certideal","group_label":"FT 120"},
      {"name":"Cooptalis","group_label":"FT 120"},
      {"name":"CorWave","group_label":"FT 120"},
      {"name":"Crosscall","group_label":"FT 120"},
      {"name":"Cubyn","group_label":"FT 120"},
      {"name":"Devialet","group_label":"FT 120"},
      {"name":"E.Z Drive","group_label":"FT 120"},
      {"name":"EcoVadis","group_label":"FT 120"},
      {"name":"ekWateur","group_label":"FT 120"},
      {"name":"Geosat","group_label":"FT 120"},
      {"name":"GitGuardian","group_label":"FT 120"},
      {"name":"Gojob","group_label":"FT 120"},
      {"name":"Happn","group_label":"FT 120"},
      {"name":"Heetch","group_label":"FT 120"},
      {"name":"HOMA","group_label":"FT 120"},
      {"name":"Hoppen","group_label":"FT 120"},
      {"name":"HR Path","group_label":"FT 120"},
      {"name":"Hubside","group_label":"FT 120"},
      {"name":"iAdvize","group_label":"FT 120"},
      {"name":"Igyxos","group_label":"FT 120"},
      {"name":"Ilek","group_label":"FT 120"},
      {"name":"ImCheck Therapeutics","group_label":"FT 120"},
      {"name":"Innovafeed","group_label":"FT 120"},
      {"name":"Inotrem","group_label":"FT 120"},
      {"name":"JobTeaser","group_label":"FT 120"},
      {"name":"Joone","group_label":"FT 120"},
      {"name":"Klaxoon","group_label":"FT 120"},
      {"name":"La Belle Vie","group_label":"FT 120"},
      {"name":"Leocare","group_label":"FT 120"},
      {"name":"Libon","group_label":"FT 120"},
      {"name":"Luko","group_label":"FT 120"},
      {"name":"Madbox","group_label":"FT 120"},
      {"name":"Medadom","group_label":"FT 120"},
      {"name":"Meilleurtaux","group_label":"FT 120"},
      {"name":"Mnemo Therapeutics","group_label":"FT 120"},
      {"name":"MWM","group_label":"FT 120"},
      {"name":"MYM","group_label":"FT 120"},
      {"name":"NW","group_label":"FT 120"},
      {"name":"Okwind","group_label":"FT 120"},
      {"name":"OpenClassrooms","group_label":"FT 120"},
      {"name":"Papernest","group_label":"FT 120"},
      {"name":"Pennylane","group_label":"FT 120"},
      {"name":"Perfectstay","group_label":"FT 120"},
      {"name":"Pharmedistore","group_label":"FT 120"},
      {"name":"Pigment","group_label":"FT 120"},
      {"name":"Platform.sh","group_label":"FT 120"},
      {"name":"PlayPlay","group_label":"FT 120"},
      {"name":"Recommerce","group_label":"FT 120"},
      {"name":"Selectra","group_label":"FT 120"},
      {"name":"Sendinblue","group_label":"FT 120"},
      {"name":"Singulart","group_label":"FT 120"},
      {"name":"Skello","group_label":"FT 120"},
      {"name":"Smallable","group_label":"FT 120"},
      {"name":"Equativ","group_label":"FT 120"},
      {"name":"SparingVision","group_label":"FT 120"},
      {"name":"Tissium","group_label":"FT 120"},
      {"name":"Tree Frog Therapeutics","group_label":"FT 120"},
      {"name":"Trusk","group_label":"FT 120"},
      {"name":"Ubitransport","group_label":"FT 120"},
      {"name":"Ultra Premium Direct","group_label":"FT 120"},
      {"name":"Vade Secure","group_label":"FT 120"},
      {"name":"Verkor","group_label":"FT 120"},
      {"name":"Virtuo","group_label":"FT 120"},
      {"name":"Visiperf","group_label":"FT 120"},
      {"name":"Wandercraft","group_label":"FT 120"},
      {"name":"Withings","group_label":"FT 120"},
      {"name":"Woosmap","group_label":"FT 120"},
      {"name":"Wynd","group_label":"FT 120"},
      {"name":"Yousign","group_label":"FT 120"},
      {"name":"Yubo","group_label":"FT 120"}
    ]$$
  ) AS (name TEXT, group_label TEXT)
)
INSERT INTO program_organizations (
  id, program_edition_id, organization_id, group_label, legacy_source,
  created_at, updated_at
)
SELECT
  uuid_generate_v4(),
  pe.id,
  o.id,
  s.group_label,
  'french_tech_next',
  NOW(),
  NOW()
FROM ft2022_programs s
JOIN organizations o ON o.slug = lower(regexp_replace(
  regexp_replace(unaccent(s.name), '[^a-zA-Z0-9\s-]', '', 'g'),
  '\s+', '-', 'g'
))
JOIN program_editions pe ON pe.slug = 'french-tech-next40-120-2022'
ON CONFLICT (program_edition_id, organization_id) DO NOTHING;
